freshermeat/web/views/organization.py
#! /usr/bin/env python
# Freshermeat - An open source software directory and release tracker.
# Copyright (C) 2017-2024 Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information: https://github.com/cedricbonhomme/freshermeat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os
import uuid
from datetime import timezone

from feedgen.feed import FeedGenerator
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import login_required

from freshermeat.bootstrap import application
from freshermeat.bootstrap import db
from freshermeat.models import Icon
from freshermeat.models import Organization
from freshermeat.web.forms import AddOrganizationForm
from freshermeat.web.views.common import admin_permission

organization_bp = Blueprint("organization_bp", __name__, url_prefix="/organization")
organizations_bp = Blueprint("organizations_bp", __name__, url_prefix="/organizations")


@organizations_bp.route("/", methods=["GET"])
def list_organizations():
    """Return the page which will display the list of organizations."""
    head_titles = ["Organizations"]
    return render_template("organizations.html", head_titles=head_titles)


@organization_bp.route("/<string:organization_name>", methods=["GET"])
def get(organization_name=None):
    """Return the organization given in parameter."""
    organization = Organization.query.filter(
        Organization.name == organization_name
    ).first()
    if organization is None:
        abort(404)
    head_titles = ["The " + organization.name + " Organization"]
    return render_template(
        "organization.html", organization=organization, head_titles=head_titles
    )


@organization_bp.route("/<string:organization_name>/releases.atom", methods=["GET"])
def recent_releases(organization_name=None):
    """Generates a feed for the releases of an organization."""
    organization = Organization.query.filter(
        Organization.name == organization_name
    ).first()
    if organization is None:
        abort(404)
    fg = FeedGenerator()
    fg.id(
        url_for(
            "organization_bp.recent_releases",
            organization_name=organization.name,
            _external=True,
        )
    )
    fg.title(f"Recent releases for {organization.name}")
    fg.link(href=request.url, rel="self")
    for project in organization.projects:
        for release in project.releases:
            fe = fg.add_entry()
            fe.id(f"{release.project.name} {release.version}")
            fe.title(f"{release.project.name} {release.version}")
            fe.description(release.changes)
            fe.link(href=release.release_url)
            fe.updated(release.published_at.replace(tzinfo=timezone.utc))
            fe.published(release.published_at.replace(tzinfo=timezone.utc))
    atomfeed = fg.atom_str(pretty=True)
    return atomfeed


@organization_bp.route("/create", methods=["GET"])
@organization_bp.route("/edit/<int:organization_id>", methods=["GET"])
@login_required
@admin_permission.require(http_exception=403)
def form(organization_id=None):
    """Returns a form for the creation/edition of organizations."""
    action = "Add an organization"
    head_titles = [action]

    form = AddOrganizationForm()

    if organization_id is None:
        return render_template(
            "edit_organization.html", action=action, head_titles=head_titles, form=form
        )

    organization = Organization.query.filter(Organization.id == organization_id).first()
    form = AddOrganizationForm(obj=organization)
    action = "Edit organization"
    head_titles = ["The " + organization.name + " organization", action]
    return render_template(
        "edit_organization.html",
        action=action,
        head_titles=head_titles,
        form=form,
        organization=organization,
    )


@organization_bp.route("/create", methods=["POST"])
@organization_bp.route("/edit/<int:organization_id>", methods=["POST"])
@login_required
@admin_permission.require(http_exception=403)
def process_form(organization_id=None):
    """Process the form for the creation/edition of organizations."""
    form = AddOrganizationForm()

    if not form.validate():
        return render_template("edit_organization.html", form=form)

    if organization_id is not None:
        organization = Organization.query.filter(
            Organization.id == organization_id
        ).first()
        # Logo
        f = form.logo.data
        if f:
            try:
                # Delete the previous icon
                icon_url = os.path.join(
                    application.config["UPLOAD_FOLDER"], organization.icon_url
                )
                os.unlink(icon_url)
                old_icon = Icon.query.filter(Icon.url == organization.icon_url).first()
                db.session.delete(old_icon)
                organization.icon_url = None
                db.session.commit()
            except Exception as e:
                print(e)

            # save the picture
            filename = str(uuid.uuid4()) + ".png"
            icon_url = os.path.join(application.config["UPLOAD_FOLDER"], filename)
            f.save(icon_url)
            # create the corresponding new icon object
            new_icon = Icon(url=filename)
            db.session.add(new_icon)
            db.session.commit()
            organization.icon_url = new_icon.url

        form.populate_obj(organization)
        try:
            db.session.commit()
            flash(
                "Organization {organization_name} successfully updated.".format(
                    organization_name=form.name.data
                ),
                "success",
            )
        except Exception:
            form.name.errors.append("Name already exists.")
        return redirect(
            url_for("organization_bp.form", organization_id=organization.id)
        )

    # Create a new organization
    new_organization = Organization(
        name=form.name.data,
        short_description=form.short_description.data,
        description=form.description.data,
        website=form.website.data,
        organization_type=form.organization_type.data,
        cve_vendor=form.cve_vendor.data,
    )
    db.session.add(new_organization)
    try:
        db.session.commit()
    except Exception:
        return redirect(
            url_for("organization_bp.form", organization_id=new_organization.id)
        )
    # Logo
    f = form.logo.data
    if f:
        # save the picture
        filename = str(uuid.uuid4()) + ".png"
        icon_url = os.path.join(application.config["UPLOAD_FOLDER"], filename)
        f.save(icon_url)
        # create the corresponding new icon object
        new_icon = Icon(url=filename)
        db.session.add(new_icon)
        new_organization.icon_url = new_icon.url
    db.session.commit()
    flash(
        "Organization {organization_name} successfully created.".format(
            organization_name=new_organization.name
        ),
        "success",
    )

    return redirect(
        url_for("organization_bp.form", organization_id=new_organization.id)
    )

freshermeat/web/views/project.py
#! /usr/bin/env python
# Freshermeat - An open source software directory and release tracker.
# Copyright (C) 2017-2024 Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information: https://github.com/cedricbonhomme/freshermeat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os
import uuid
from datetime import timezone

from feedgen.feed import FeedGenerator
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from werkzeug.exceptions import BadRequest

from freshermeat.bootstrap import application
from freshermeat.bootstrap import db
from freshermeat.models import Code
from freshermeat.models import Feed
from freshermeat.models import get_or_create
from freshermeat.models import Icon
from freshermeat.models import Language
from freshermeat.models import License
from freshermeat.models import Organization
from freshermeat.models import Project
from freshermeat.models import Tag
from freshermeat.web.forms import AddProjectForm
from freshermeat.web.forms import CodeForm
from freshermeat.web.forms import FeedForm
from freshermeat.web.utils.misc import similar_projects
from freshermeat.web.utils.spawn import ERRORS

project_bp = Blueprint("project_bp", __name__, url_prefix="/project")
projects_bp = Blueprint("projects_bp", __name__, url_prefix="/projects")


@projects_bp.route("/", methods=["GET"])
def list_projects():
    """Return the page which will display the list of projects."""
    head_titles = ["Projects"]
    return render_template("projects.html", head_titles=head_titles)


@project_bp.route("/<string:project_name>", methods=["GET"])
def get(project_name=None):
    """Return the project given in parameter."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    similar = similar_projects(project)
    head_titles = ["The " + project.name + " Open Source Project"]
    return render_template(
        "project.html", project=project, similar=similar, head_titles=head_titles
    )


@project_bp.route("/<string:project_name>/delete", methods=["GET"])
@login_required
def delete(project_name=None):
    """Delete a project."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    db.session.delete(project)
    db.session.commit()
    flash("Project deleted.", "success")
    return redirect(url_for("projects_bp.list_projects"))


@project_bp.route("/<string:project_name>/settings", methods=["GET"])
def settings(project_name=None):
    """Return the settings page."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    head_titles = ["The " + project.name + " Open Source Project", "Settings Page"]
    return render_template("settings.html", project=project, head_titles=head_titles)


@project_bp.route("/<string:project_name>/code", methods=["GET"])
def code_locations(project_name=None):
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    form = CodeForm()
    return render_template("code.html", project=project, form=form)


@project_bp.route("/<string:project_name>/code", methods=["POST"])
@login_required
def code_locations_process(project_name=None):
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    form = CodeForm()
    if not form.validate():
        return render_template("code.html", project=project, form=form)
    new_code = Code(
        repository_url=form.repository_url.data,
        scm_type=form.scm_type.data,
        project_id=project.id,
    )
    db.session.add(new_code)
    try:
        db.session.commit()
        flash("New location successfully created.", "success")
    except Exception:
        flash("Impossible to add a new location.", "success")
    return render_template("code.html", project=project, form=form)


@project_bp.route("/<string:project_name>/releases", methods=["GET"])
def edit_releases(project_name=None):
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    return render_template("edit_releases.html", project=project)


@project_bp.route("/<string:project_name>/feeds", methods=["GET"])
def feed(project_name=None):
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    feeds = Feed.query.filter(Feed.project_id == project.id)
    form = FeedForm()
    return render_template("feed.html", project=project, feeds=feeds, form=form)


@project_bp.route("/<string:project_name>/feeds", methods=["POST"])
@login_required
def feed_locations_process(project_name=None):
    """Process the new f"""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    feeds = Feed.query.filter(Feed.project_id == project.id)
    form = FeedForm()
    if not form.validate():
        return render_template("feed.html", project=project, feeds=feeds, form=form)
    new_feed = Feed(link=form.link.data, project_id=project.id)
    db.session.add(new_feed)
    try:
        db.session.commit()
        flash("New feed successfully created.", "success")
    except Exception:
        flash("Impossible to add a new feed.", "success")
    return render_template("feed.html", project=project, feeds=feeds, form=form)


@project_bp.route("/<string:project_name>/releases.atom", methods=["GET"])
def recent_releases(project_name=None):
    """Generates a feed for the releases."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    fg = FeedGenerator()
    fg.id(
        url_for("project_bp.recent_releases", project_name=project.name, _external=True)
    )
    fg.title(f"Recent releases for {project.name}")
    fg.link(href=request.url, rel="self")
    for release in project.releases:
        fe = fg.add_entry()
        fe.id(f"{release.project.name} {release.version}")
        fe.title(f"{release.project.name} {release.version}")
        fe.description(release.changes)
        fe.link(href=release.release_url)
        fe.updated(release.published_at.replace(tzinfo=timezone.utc))
        fe.published(release.published_at.replace(tzinfo=timezone.utc))
    atomfeed = fg.atom_str(pretty=True)
    return atomfeed


@project_bp.route("/<string:project_name>/cves.atom", methods=["GET"])
def recent_cves(project_name=None):
    """Generates a feed for the CVEs."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    fg = FeedGenerator()
    fg.id(url_for("project_bp.recent_cves", project_name=project.name, _external=True))
    fg.title(f"Recent CVEs for {project.name}")
    fg.link(href=request.url, rel="self")
    for cve in project.cves:
        fe = fg.add_entry()
        fe.id(cve.cve_id)
        fe.title(f"{cve.project.name} - {cve.cve_id}")
        fe.description(cve.summary)
        fe.link(href="https://cvepremium.circl.lu/cve/" + cve.cve_id)
        fe.updated(cve.published_at.replace(tzinfo=timezone.utc))
        fe.published(cve.published_at.replace(tzinfo=timezone.utc))
    atomfeed = fg.atom_str(pretty=True)
    return atomfeed


@project_bp.route("/<string:project_name>/news.atom", methods=["GET"])
def recent_news(project_name=None):
    """Generates a feed for the news."""
    project = Project.query.filter(Project.name == project_name).first()
    if project is None:
        abort(404)
    fg = FeedGenerator()
    fg.id(url_for("project_bp.recent_news", project_name=project.name, _external=True))
    fg.title(f"Recent news for {project.name}")
    fg.link(href=request.url, rel="self")
    for a_news in project.news:
        fe = fg.add_entry()
        fe.id(a_news.entry_id)
        fe.title(f"{a_news.project.name} - {a_news.title}")
        fe.description(a_news.content)
        fe.link(href=a_news.link)
        fe.updated(a_news.published.replace(tzinfo=timezone.utc))
        fe.published(a_news.published.replace(tzinfo=timezone.utc))
    atomfeed = fg.atom_str(pretty=True)
    return atomfeed


@project_bp.route("/create", methods=["GET"])
@project_bp.route("/edit/<int:project_id>", methods=["GET"])
@login_required
def form(project_id=None):
    """Returns a form for the creation/edition of projects."""
    action = "Add a project"
    head_titles = [action]

    form = AddProjectForm()
    form.organization_id.choices = [(0, "")]
    form.organization_id.choices.extend(
        [(org.id, org.name) for org in Organization.query.all()]
    )

    # Create a new project
    if project_id is None:
        return render_template(
            "edit_project.html", action=action, head_titles=head_titles, form=form
        )
    # Edit an existing project
    project = Project.query.filter(Project.id == project_id).first()
    form = AddProjectForm(obj=project)
    form.organization_id.choices = [(0, "")]
    form.organization_id.choices.extend(
        [(org.id, org.name) for org in Organization.query.all()]
    )

freshermeat/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <br />
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h1 class="display-4">{% if config.FRESHERMEAT_INSTANCE_NAME  %}{{ config.FRESHERMEAT_INSTANCE_NAME }}{% else %}Freshermeat{% endif %}</h1>
      <p class="lead">This website is a directory of open source
        software and tools related to security.
        It is powered by
        <a href="https://github.com/cedricbonhomme/freshermeat" target="_blank" rel="noopener noreferrer">Freshermeat</a>.</p>
        <hr class="my-4" />
      </div>
      <div class="col-md-4 text-justify">
        <p>You are welcome to copy, modify or redistribute the
          <a href="https://github.com/cedricbonhomme/freshermeat" target="_blank" rel="noopener noreferrer">source code</a> of Freshermeat
          according to the <a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank" rel="noopener noreferrer">Affero</a> GPL license.</p>
          <p>All content (descriptions of projects) is licensed under CC-BY-SA.</p>
        </div>
        <div class="col-md-12">
          <hr class="my-4" />
        </div>
      </div>
      <div class="row justify-content-between">
        <div class="col-md-4">
          <p class="text-justify">The Open Source Security Software directory is an open database.<br />
            You can contribute to this directory by
            <a href="{{ url_for('submission_bp.form_submission') }}">submitting</a>
            an open source security project.</p>
          </div>
          <div class="col-md-4 text-justify">
            <p class="text-justify">Members can add new projects to the directory with a bookmarklet. Just add the following link to your browser's bookmarks.</p>
            <a href="javascript:if(document.getSelection){s=document.getSelection();}else{s='';};document.location='{{ url | instance_domain_name }}/project/bookmarklet?url='+encodeURIComponent(document.location)+'&name='+encodeURIComponent(document.title)" class="btn btn-primary" role="button" aria-pressed="true">Add this project to Freshermeat</a>
          </div>
          <div class="col-md-4">
            Check the <a href="{{ url_for('apiv2.doc') }}">documentation of the API</a>.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

freshermeat/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Freshermeat - {{ config.FRESHERMEAT_INSTANCE_NAME }}" />
  <meta name="author" content="Cédric Bonhomme" />
  <link href="{{ url_for('recent_releases') }}" rel="alternate" title="Recent releases" type="application/atom+xml" />
  <link href="{{ url_for('recent_cves') }}" rel="alternate" title="Recent CVEs" type="application/atom+xml" />
  <link href="{{ url_for('recent_news') }}" rel="alternate" title="Recent news" type="application/atom+xml" />
  {% block head_css %}
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/bootstrap/dist/css/bootstrap.min.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/bootstrap-select/dist/css/bootstrap-select.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='npm_components/fork-awesome/css/fork-awesome.min.css') }}" />
  {% endblock %}
  <script src="{{ url_for('static', filename='npm_components/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/popper.js/dist/umd/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/datatables.net/js/jquery.dataTables.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/datatables.net-bs4/js/dataTables.bootstrap4.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/lodash/lodash.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/chart.js/dist/chart.umd.js') }}"></script>
  <script src="{{ url_for('static', filename='js/utils.js') }}"></script>
  <script src="{{ url_for('static', filename='js/templates.js') }}"></script>
  <title>{% if head_titles %}{{ ' - '.join(head_titles + ['']) }}{% endif %}
    {% if config.FRESHERMEAT_INSTANCE_NAME %}{{ config.FRESHERMEAT_INSTANCE_NAME }}{% else %}Freshermeat{% endif %}
    {% if head_titles_tail %}{{ ' - '.join([''] + head_titles_tail) }}{% endif %}</title>
  {% endblock %}
</head>
{% block page_body %}
<body>
  {% block main_menu %}
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand d-inline-block  text-truncate" href="/">{% if config.FRESHERMEAT_INSTANCE_NAME  %}{{ config.FRESHERMEAT_INSTANCE_NAME }}{% else %}Freshermeat{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars fa-2"></span>
    </button>

    {% block menu_links %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto w-100 justify-content-end">
        {% if not current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('projects_bp.list_projects') }}" title="Projects">Projects</a>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Projects</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('projects_bp.list_projects') }}" title="Projects">List projects</a>
            <a class="dropdown-item" href="{{ url_for('project_bp.form') }}">Add new project</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item">
              <form action="{{ url_for('project_bp.import_project', import_from='gitlab') }}" class="form-row input-inline" method="GET" name="import">
                <div class="input-group mb-3">
                  <input class="form-control" type="url" name="project" id="inlineFormInputGroupGitLab" placeholder="GitLab link" aria-label="GitLab link" required />
                  <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary"><i class="fa fa-download" title="Import from GitLab"></i></button>
                  </div>
                </div>
              </form>
            </a>
            <a class="dropdown-item">
              <form action="{{ url_for('project_bp.import_project', import_from='github') }}" class="form-row input-inline" method="GET" name="import">
                <div class="input-group mb-3">
                  <input class="form-control" type="url" name="project" id="inlineFormInputGroupGitHub" placeholder="GitHub link" aria-label="GitHub link" required />
                  <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary"><i class="fa fa-download" title="Import from GitHub"></i></button>
                  </div>
                </div>
              </form>
            </a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('organizations_bp.list_organizations') }}" title="Organizations">Organizations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('stats_bp.stats') }}" title="Statistics">Statistics</a>
        </li>
        {% if current_user.is_authenticated %}
        {% if current_user.is_admin %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cogs" aria-hidden="true"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ url_for('admin_bp.dashboard') }}">Dashboard</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin_bp.list_users') }}">Users</a>
            <a class="dropdown-item" href="{{ url_for('submissions_bp.list_submissions') }}">Submissions</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/admin">Data</a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownUser">
            <span class="dropdown-item" title="Schemas"><span class="text-muted">Signed in as</span><br /><b>{{ current_user.login }}</b></span>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('user_bp.form') }}" title="Profile">Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('logout') }}" title="Sign out">Sign out</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('about') }}" title="About">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('login') }}" title="Sign in"><i class="fa fa-sign-in" aria-hidden="true"></i></a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% endblock %}
  </nav>
  {% endblock %}


  <div class="container alert-message">
    {% block messages %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <br />
    {% for category, message in messages %}
    <div class="alert alert-{{category}}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% endblock %}
  </div>
  {% block content %}{% endblock %}
  <br />
  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <a href="{{ url_for('about') }}" >About</a>
        </div>
      </div>
    </div>
  </footer>
</body>
{% endblock %}
</html>

freshermeat/templates/settings.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h3>Settings</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <a href="{{ url_for('project_bp.form', project_id=project.id) }}">Edit project description</a>
          <p class="text-justify">Edit the title, description, licenses, tags, etc. of the project.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <a href="{{ url_for('project_bp.code_locations', project_name=project.name) }}">Edit code locations</a>
          <p class="text-justify">Management of code locations (Git, Mercurial, etc.).</p>
        </div>
      </div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <a href="{{ url_for('project_bp.edit_releases', project_name=project.name) }}">Edit project releases</a>
          <p class="text-justify">Management of releases.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <a href="{{ url_for('project_bp.feed', project_name=project.name) }}">Edit project feeds</a>
          <p class="text-justify">For the fetching of news (RSS and ATOM) related to the project.</p>
        </div>
      </div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <a href="{{ url_for('project_bp.delete', project_name=project.name) }}" onclick="return confirm('You are going to delete this project.');">Delete this project</a>
        </div>
      </div>
    </div>
  </div>
</div><!-- /.container -->
{% endblock %}